openapi: "3.0.0"

info:
  version: 0.0.3
  title: HRXP Archive API

tags:
  - name: Channels

paths:
  /channels:
    get:
      tags: [Channels]
      summary: Returns a list of all channels
      responses:
        200:
          description: OK; data in response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Channel"
  /channels/{channelId}/messages:
    parameters:
      - $ref: "#/components/parameters/channelId"
    get:
      tags: [Channels]
      summary: Return a specific channel's messages
      responses:
        200:
          description: OK; data in response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Message"
/auth/access_token:
  post:
  tags: [Auth]
  summary: exchange a Slack OAuth authorization code for a JWT
  requestBody:
    description: Payload that includes the OAuth Authorization Code from Slack
    content:
      application/json:
        schema:
          type: object
          properties:
            code:
              type: string
  responses:
    200:
      description: success! JWT in response
components:
  schemas:
    Channel:
      type: object
      properties:
        _id:
          type: string
          example: edveevere2323dc3
        slackId:
          type: string
          example: C035Z8YT7
        name:
          type: string
          example: general
        topic:
          type: string
          example: Mission 1st, People Always.
        purpose:
          type: string
          example: This channel is for alumni of all Hack Reactor campuses.
        members:
          type: array
          items:
            $ref: "#/components/schemas/User/properties/_id"
        isArchived:
          type: boolean
          default: false
    Message:
      type: object
      properties:
        _id:
          type: string
          example: a55dd3e2-1b1c-4ee8-a05e-9a35dda5710a
        ts:
          $ref: "#/components/schemas/__Timestamp"
        type:
          type: string
          example: thread
        channelName:
          type: string
          example: general
        channelId:
          type: string
          example: a55dd3e2-1b1c-4ee8-a05e-9a35dda5710a
        text:
          type: string
          example: Happy Monday, everyone!
        files:
          type: array
          items:
            type: object
            properties:
              _id:
                type: string
                example: a55dd3e2-1b1c-4ee8-a05e-9a35dda5710a
              slackId:
                type: string
                example: FJ0UW704
              displayName:
                type: string
                example: contractor-description.pdf
              fileType:
                type: string
                example: pdf
              downloadUrl:
                type: string
                format: url
                example: "https://hrxp.com/static/files/FJ0UW704E/contractor-description.pdf"
        replies:
          type: array
          items:
            properties:
              _id:
                type: string
                example: a55dd3e2-1b1c-4ee8-a05e-9a35dda5710b
              createdBy:
                $ref: "#/components/schemas/User"
              ts:
                $ref: "#/components/schemas/__Timestamp"
              text:
                type: string
              type:
                type: string
                example: reply
              channelName:
                type: string
                example: general
              channelId:
                type: string
                example: a55dd3e2-1b1c-4ee8-a05e-9a35dda5710a
              files:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      example: a55dd3e2-1b1c-4ee8-a05e-9a35dda5710a
                    slackId:
                      type: string
                      example: FJ0UW704
                    displayName:
                      type: string
                      example: contractor-description.pdf
                    fileType:
                      type: string
                      example: pdf
                    downloadUrl:
                      type: string
                      format: url
                      example: "https://hrxp.com/static/files/FJ0UW704E/contractor-description.pdf"
        createdBy:
          $ref: "#/components/schemas/User"
    User:
      type: object
      properties:
        _id:
          type: string
          example: a55dd3e2-1b1c-4ee8-a05e-9a35dda5710a
        slackId:
          type: string
          example: U07AT4FB4
        profilePhoto:
          type: string
          example: "https://hrxp.com/static/avatars/U07AT4FB4.png"
        displayName:
          type: string
          example: "Kyle Shockey [HR26]"
        realName:
          type: string
          example: Kyle Shockey

    # UTILITY SCHEMAS, which are just broken out for reusability

    __Timestamp:
      type: string
      example: "1501536037.682405"

  parameters:
    channelId:
      name: channelId
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/Channel/properties/_id"
